#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=0.13.29

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml

COPY target/healthcare-claims-processing.dar /home/daml/

# Need the root user to set appropriate ownership of the DAR file.
USER root
RUN chown daml healthcare-claims-processing.dar
USER daml

EXPOSE 7600

CMD ~/.daml/bin/daml sandbox -- --port 7600 --scenario DemoOnboardScenario.InsurancePolicies:insurancePoliciesSetSingle healthcare-claims-processing.dar
