#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=1.0.0

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml

COPY --chown=daml \
     target/healthcare-claims-processing.dar \
     scripts/ledger_setup.sh \
     /home/daml/

USER root
RUN chown daml healthcare-claims-processing.dar
USER daml

EXPOSE 6865

CMD ./ledger_setup.sh localhost 6865 healthcare-claims-processing.dar DemoOnboardScenario.StartScript:insurancePoliciesSetSingle & \
    ~/.daml/bin/daml sandbox -- --static-time --address 0.0.0.0 --port 6865 healthcare-claims-processing.dar