# This file has been generated by node2nix 1.9.0. Do not edit!

# editted for daml-js and remove pkg default

{ pkgs
, daml-js
, nodejs ? pkgs."nodejs-15_x"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv lib python2 runCommand writeTextFile;
    inherit pkgs nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
in
import ./node-packages.nix {
  inherit (pkgs) fetchurl nix-gitignore writeText runCommand stdenv lib fetchgit;
  inherit nodeEnv daml-js;
}
